### ISSUE TITLE
Allow padding the last QR

### ISSUE THREAD

**Issue by Sjors** [coinkite/BBQr#3]
> Version 27 (125 x 125 pixels) offers up to 1062 bytes of useful payload per QR, so it is a good sweet spot to consider. A simple implementation would split file into 1k (1024) blocks, with one runt, and can be sure that verison 27 QR will hold all the blocks.

> Since the typical Bitcoin wire transaction is less than 500 bytes, most finalized transactions will be encoded in a single QR with no header or other overhead needed.

In the example:

> All but final QR holds 1000 bytes when decoded, and will be 2007 characters in length.

I suggest to allow padding the last QR. Since the data length is not encoded, you can't use zeros for this padding, but any character that's part of the set `0-9A-Z$%*+-./:`, and _not_ part of hex (`0-9A-F`) and bech32 can be used. I.e. `IO$%*+-./:`. My suggestion would be `.`, because it keeps things human readable. (I suggest in any case not using `I` or `O` because that makes a future "lazy just do plain alphanumeric text" standard impossible.)

This makes life easier for UI developers: they can just format their layout for a 125 x 125 QR code. The last image won't look weird, without having to do math to figure out the right size. And a consistent size for every transaction is nice for users in general.

**Comment by doc-hex** [comment]
The QR rendering libraries I use allow me to control the "version number" (density) of the QR being generated. So I just give it the same version number for all the QR's including the last one. The final one will look the same as the others, but has wasted space and/or more error correction.

**Comment by Sjors** [comment]
Oh if that works for all / most libraries, that's even better.

**Comment by doc-hex** [comment]
Yup, in "Notes"

> - It is visually jarring to have the final QR be a different version (resolution) than
  the other ones. You should force the QR version to be the same in the whole series.
